services:
  mlflow-backend-store:
    image: postgres:14.0
    container_name: mlflow-backend-store
    environment:
      POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
    volumes:
      - mlflow_mlflow-backend-store:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "mlflowuser", "-d", "mlflowdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - model_pipeline
    restart: always

  mlflow-artifact-store:
    image: minio/minio
    container_name: mlflow-artifact-store
    ports:
      - ${MINIO_DATA_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
    volumes: 
      - mlflow_mlflow-artifact-store:/data/minio
    restart: always
    command: "server /data/minio --console-address :9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - model_pipeline

  mlflow-server:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: mlflow-server
    depends_on:
      mlflow-backend-store:
        condition: service_healthy
      mlflow-artifact-store:
        condition: service_healthy
    ports:
      - "${MLFLOW_CONSOLE_PORT}:8080"
      - "8800:80"
      - "${MLFLOW_API_PORT}:8889"
      - "8887:8887"
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      MLFLOW_S3_ENDPOINT_URL: http://mlflow-artifact-store:9000
      MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING: ${IS_SYSTEM_METRIC_ON}
    entrypoint: ["/bin/sh", "/mlflow/entrypoint.sh"]
    networks:
      - model_pipeline
    restart: always


volumes:
  mlflow_mlflow-backend-store:
    external: true
  mlflow_mlflow-artifact-store:
    external: true
  mlflow_ml-predict-result:
    external: true
  model_pipeline_shared-volume:
    external: true

networks:
  model_pipeline:
    external: true